server:
  port: 8080

spring:
  application:
    name: dopad-application
  datasource:
    url: jdbc:postgresql://localhost:5432/dopad
    username: dopad-app
    password: dopad-app
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1

queries:
  sql:
    user-dao:
      insert:
        user: >
          INSERT INTO dopad_platform.user (id, username, password) 
          VALUES (?, ?, ?)
      select:
        user-by-id: >
          SELECT * FROM dopad_platform.user WHERE id = ?
        user-by-username: >
          SELECT * FROM dopad_platform.user WHERE username = ?
    page-dao:
      insert:
        page: >
          INSERT INTO dopad_platform.page (id, owner_id, title, text, status, change_code, upload_date, is_private) 
          VALUES (?, ?, ?, (to_json(?::jsonb)), ?::page_status, ?, ?, ?)
      select:
        page-by-id: >
          SELECT * FROM dopad_platform.page WHERE id = ?
    page-membership-dao:
        insert:
          page-membership: >
            INSERT INTO dopad_platform.page_membership (id, page_id, user_id, status) 
            VALUES (?, ?, ?, ?::page_membership_status)
        select:
          page-membership-by-id: >
            SELECT * FROM dopad_platform.page_membership WHERE id = ?
          page-membership-by-page-id-and-user-id: >
            SELECT * FROM dopad_platform.page_membership WHERE page_id = ? AND user_id = ?
          page-membership-by-page-id: >
            SELECT * FROM dopad_platform.page_membership WHERE page_id = ?
        update:
          page-membership-status-by-id: >
            UPDATE dopad_platform.page_membership SET status = ?::page_membership_status WHERE id = ?
        delete:
          page-membership-by-id: >
            DELETE FROM dopad_platform.page_membership WHERE id = ?
